# Generated by Django 5.2.4 on 2025-07-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='aprobado_por_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En Revisión'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='url_imagen_portada',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_resource',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('VIDEO', 'Video'), ('QUIZ', 'Quiz'), ('SIMULATOR', 'Simulador'), ('ACTIVITY', 'Actividad'), ('FORUM', 'Foro'), ('PDF', 'Documento PDF'), ('PPT', 'Presentación PPT')], default='TEXT', max_length=20),
        ),
    ]
